spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username:
    password:
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false